export type Canvas = {
  id: number;
  name: string;
  description?: string;
  max_artworks_per_user_per_hour: number;
  artwork_expiry_minutes: number;
  min_visibility_minutes?: number;
  placement_fee: number;
  created_at: string;
  grid_size: number;
  is_active?: boolean;
  max_x?: number;
  max_y?: number;
  min_x?: number;
  min_y?: number;
  premium_zone_enabled?: boolean;
  background_color?: string;
  theme?: string;
  total_artworks_placed: number;
  total_artworks_collected: number;
  active_artworks_count: number;
};
